### PR TITLE
Quote-Button

### PR DESCRIPTION
**Pull request by loesler**
- removed quote link
- added new quote button
- see https://github.com/ilosuna/mylittleforum/issues/474

- Styling is missing, for that reason, work in progress is added

### CODE REVIEW

**Comment by loesler** [comment]
I remembered the function [createInputElementWithAttributes](https://github.com/ilosuna/mylittleforum/blob/master/js/main.js#L137) - and... I haven't questioned it. ;-) Do you prefer a button element instead of the input?

**Comment by auge8472** [comment]
> Do you prefer a button element instead of the input?

Yes, I do. It makes the handling of the CSS a bit simpler because the text of the button is textContent and not it's value and it's also because of this the modern version.

`<input type="button" value="quote message" />` versus `<button type="button">quote message</button>`.

**Comment by loesler** [comment]
I replaced the input element by a button, i.e.,

`<button type="button" id="insert-quote" title="Insert quoted text of the posting to be replied on" tabindex="-1">quote message</button>`

**Comment by auge8472** [comment]
I'll add the styling with a separate pull request.

**Pull request merged**
