### PR TITLE
Handling of the read state in entry thread

### PR DESCRIPTION
**Pull request by derletztekick**
- Handling of the read state in entry thread by using code from
thread.inc.php
- Could not interpret the former code line 'if($data['pid']==0)'
- see https://github.com/ilosuna/mylittleforum/pull/233
- https://github.com/ilosuna/mylittleforum/issues/245

### CODE REVIEW

**Comment by derletztekick** [comment]
Please check the former line of codes and its integration especially the line 'if($data['pid']==0)', i.e. https://github.com/ilosuna/mylittleforum/pull/251/files#diff-fe37dd6564d0036b00370f87c4d9e584L155

**Comment by auge8472** [comment]
I'm not gone. I'll take a look into this.

**Comment by auge8472** [comment]
> Please check the former lines of code and its integration especially the line `if($data['pid']==0)`.

I checked now the code with `if($data['pid']==0)`. The block distinguishes between the thread-opening-entry and any answer to show the red thread-box-icon in front of the opening posting in case of a new answer since the last visit (detected with the cookie value).

Is it really useful to show the red thread-box-icon in front of the opening posting in case of an answer? The answer itself is marked as new with the red arrow and that's correct, The thread opener is also marked as new with the red thread-box-icon, but it isn't new. It "only" has (a) new answer(s). The answer could be part of a deep branch and therefore outside the viewport when one sees the red arrow in front of the thread opener. So it's not really a help for identifying the new entry/entries.

Anyway, in the `index.inc.php`, where we also display the thread trees ([lines 127 ff](https://github.com/ilosuna/mylittleforum/blob/master/includes/index.inc.php#L127)), I also abandoned the code for displaying the red thread-box-icon in front the opening posting in case of an answer.

How to unify these different behaviours?

**Comment by derletztekick** [comment]
Hi Auge,

> I also abandoned the code for displaying the red thread-box-icon in front the opening posting in case of an answer.
Hmm, okay. Are you agree to merge the changed code? If not, can you add the missing part (`if($data['pid']==0)`)?


> Would it not be wise to transfer the code into a function?
I think, it will be difficult (handling/combining the array and the session values) or do you mean something like that:

```
function foo($data, $last_visit) {
	if ($data['req_user'] !== NULL and is_numeric($data['req_user'])) {
		$data['is_read'] = true;
		$data['new'] = false;
	} else {
		$data['is_read'] = false;
		if (isset($_SESSION[$settings['session_prefix'].'usersettings']['newtime']) && $_SESSION[$settings['session_prefix'].'usersettings']['newtime'] < $data['time'] || ($last_visit && ($data['last_reply'] > $last_visit or $data['time'] > $last_visit))) {
			$data['new'] = true;
		} else {
			$data['new'] = false;
		}
	}
	return $data;
}
```

**Comment by auge8472** [comment]
> Hmm, okay. Are you agree to merge the changed code? If not, can you add the missing part (`if($data['pid']==0)`)?

Let's merge the change but hold the issue #245 open. So we have a solution and can think about the structure of a function.

> > Would it not be wise to transfer the code into a function?
> 
> I think, it will be difficult (handling/combining the array and the session values) or do you mean something like that: …

Yes, that would be *in general* a solution.

**Pull request merged**
