### PR TITLE
show number of unlocked users

### PR DESCRIPTION
**Pull request by derletztekick**
- SQL-SELECT is added to count the number of unlocked users
- Number of unlocked users is shown in sidebar
- Issue: https://github.com/ilosuna/mylittleforum/issues/62

### CODE REVIEW

**Comment by derletztekick** [comment]
If I'm finished, I will reopen the branch.

**Comment by auge8472** [comment]
Please rethink the key names for the language strings. A user, who waits for the release of his account is not an **un**locked_user(s_link). The english text is a bit misleading too. It says `[counter] unlocked user(s)`, where counter will be replaced with the number of not released user accounts. These users are not unlocked, they *have to be* unlocked.

My problem: I can't deliver a better translation. Google translator tells me status 403 :-(

**Comment by derletztekick** [comment]
Okay. Suggestion: _[counter] locked user(s)_

**Comment by auge8472** [comment]
I like the second one.

**Comment by derletztekick** [comment]
I believe, the better one is: _[counter] non-activated user(s)_
I merge my solution to the master branch. Thus, you can edit the phrase by yourself.

non-activated-users

**Pull request merged**
