### PR TITLE
Improve spanish lang

### PR DESCRIPTION
**Pull request by vihuna**
I'm going to divide it in 4 sub-tasks (for clarity):

- [X] Restore accent marks and other punctuation signs; correct some typos.
- [X] Informal address unification; some expression improvements.
- [X] Non translated / Wrongly translated items.
- [X] Uppercase/lowercase unification.
- [X] Miscellaneous issues.

Each one of the four first sub-tasks will be a single commit respectively.
The last sub-task will be more granular with respect to the commits.

### CODE REVIEW

**Comment by vihuna** [comment]
Should I remove deprecated items like [this](https://github.com/ilosuna/mylittleforum/blob/master/lang/spanish.lang#L764-L767)? It seems they are not present in English translation.

**Comment by loesler** [comment]
> Should I remove deprecated items like [this](https://github.com/ilosuna/mylittleforum/blob/master/lang/spanish.lang#L764-L767)? It seems they are not present in English translation.

Yes, I think one should remove such items. Thank you.

**Comment by vihuna** [comment]
I think that's all I had in mind.

**Comment by auge8472** [comment]
When it's done, it's done. Thank you.

**Pull request merged**
