### PR TITLE
Update functions.inc.php

### PR DESCRIPTION
**Pull request by masju1**
Works with PHP 7.3, better compatibility?

### CODE REVIEW

**Comment by loesler** [comment]
> Works with PHP 7.3

Works since [PHP 5 >= 5.2.0](https://www.php.net/manual/de/function.filter-var.php), but with some [restrictions](https://www.php.net/manual/de/function.filter-var.php#112492).  However, I believe, your implementation is more useful that an regexp. Thank you for your effort.

**Comment by auge8472** [comment]
*Only as a note.*

There is a further restriction. `filter_var` does not support [IDN](https://en.wikipedia.org/wiki/Internationalized_domain_name) (domain names with non latin chars) because the filter is based on RFC 822 which is from 1982. I don't know if IDN domains are in common use for e-mail-addresses (it's not the case in Germany) but it *could* possibly break in some countries. Thatswhy we did not switch to filter_var until now.

**Comment by loesler** [comment]
Should I roll back?

**Comment by auge8472** [comment]
> Should I roll back?

No, let's wait for reports. Maybe my assumptions are baseless.

**Comment by loesler** [comment]
Okay!

**Pull request merged**
