### PR TITLE
Update swedish.lang

### PR DESCRIPTION
**Pull request by danielb987**
Update the swedish language file

### CODE REVIEW

**Comment by loesler** [comment]
Thank you for improving the lang file! Tack! ;)

**Comment by danielb987** [comment]
You are welcome!  :)

How do I update the swedish language file for version 2.4.x? I have a [swedish language file](https://www.jvmv2.se/forum/lang/swedish.lang) for version 2.4.20.

**Comment by loesler** [comment]
Was your changed lang file for 2.4.20? If yes, you don't need to provide a further one. Your changes will be included to the next release.

**Comment by danielb987** [comment]
> Was your changed lang file for 2.4.20? If yes, you don't need to provide a further one. Your changes will be included to the next release.

I created a fork of the `mylittleforum` repository and then cloned it to my local computer and copied the 2.4.20 language file to the GitHub folder. But then I discovered that there was several changes. New keys had been added and some keys had been removed.

So this file is not the same as the 2.4.20 file.

See this branch for the difference between 2.4.20 and master on the english and swedish language files:
https://github.com/ilosuna/mylittleforum/compare/master...danielb987:version_2_4_20

I now see that you have a legacy_2.4 branch. Should i do a PR to that branch with the 2.4.20 swedish language file?

**Comment by loesler** [comment]
Usually, we commit to the master branch all new files or changes. So, we do not support former versions. The legacy_2.4 branch was created by @auge8472 to handle changes for version 2.4 as well as for the upcoming 2.5. However, we do not update versions below the current version.

So, if you have a lang file that is related to the latest version (2.4.20) and which differs to the file provided in this branch, please create a new branch and upload the changes. I think, this is the easiest way.

**Pull request merged**
