### PR TITLE
Avatar handling

### PR DESCRIPTION
**Pull request by loesler**
- add getAvatar on several placed to handle name convention
- Overwrite https://github.com/ilosuna/mylittleforum/pull/352 because it
is incomplete and due to a conflict in editing this issue

### CODE REVIEW

**Comment by auge8472** [comment]
Oh, there was more than one place to edit. Thank you for your correction and enhancements.

**Comment by loesler** [comment]
No problem!

**Comment by auge8472** [comment]
Did you merged it into the master branch or into the branch legacy_2.4?

**Comment by loesler** [comment]
I merged the changes into master.

**Comment by loesler** [comment]
Should I add it to both, the master and the legacy_2.4?

**Comment by auge8472** [comment]
I'll add today it with a cherry pick.

**Comment by loesler** [comment]
Thank you!

**Comment by auge8472** [comment]
Done. I was enforced to commit your changes instead to do a cherry pick because of a merge conflict. Thatswhy my name gets mentioned as author. I mentioned you as the author in the commit message.

**Pull request merged**
