### PR TITLE
Fix: closing behavior

### PR DESCRIPTION
**Pull request by derletztekick**
Fix for closing issue, cf.
http://mylittleforum.net/forum/index.php?id=8428 The window will not
close, if the scollbar inside the preview element is clicked.

### CODE REVIEW

**Comment by auge8472** [comment]
I will put the changes into my own installation and test it, because I expect the line 848 not to be the only one, that causes a message about a type error. The first occurence, that leads to my issue #35, stated a different variable name than `templatePath`.

**Comment by derletztekick** [comment]
> that causes a message about a type error.
Yes, that is possible. But up to now, I cannot reproduce the message using FF and Opera. [Ctrl] + [Shift] + [J] or [Ctrl] + [Shift] + [K] open the console but there is no warning message or some other entries. I'm sorry. Maybe I have to configure the console output (errors and warnings are enabled), see [screen shot](https://picload.org/image/rdacipcd/mlf.png)

**Comment by auge8472** [comment]
I implemented you change regarding the type error in my test forum, resulting in no further warning message about the type-thing. Only a warning, not to use `windows.controllers` anymore, leaves.

I'll merge your PR. Thank you.

**Comment by derletztekick** [comment]
Again, I'm sorry. `windows.controllers` is not used by the javascript. Are you sure that the message is produced by the forum and not by an FF extension or something like that?

**Comment by auge8472** [comment]
That's possible.

**Pull request merged**
