### PR TITLE
Remove item

### PR DESCRIPTION
**Pull request by derletztekick**
- remove duplicate item 'auto_lock_old_threads' in setting table

### CODE REVIEW

**Comment by auge8472** [comment]
I think, this is not a good solution. If the setting exists only once (target state), then **this one** line will be removede from the database. If we restore the settigns table (see #99), the doublette of the setting overwrites it's first occurance in the array and only one setting (the second occurance) will be restored to the database. I think, this would be teh better solution.

**Comment by derletztekick** [comment]
> If the setting exists only once

How is it possible?

**Comment by auge8472** [comment]
> > If the setting exists only once
> How is it possible?
I would expect the setting to exists only once in *most* of the installations.

**Comment by derletztekick** [comment]
At witch time we duplicate the value?

**Comment by auge8472** [comment]
> At witch time we duplicate the value?

description follows on #99. Let's discuss it solely there.

**Pull request merged**
